name = "SMP 2026"
author = "TI7AN"
version = "1.2.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fae7675863ef52d5daf7bb06f95a84aa65192570178d7b0fe77b8967513aa63a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"

[options]
datapack-folder = "datapacks"
