name = "SMP 2026"
author = "TI7AN"
version = "1.1.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4cdb116b37a1ecaabcb521f9f7a2f21e57c1e62081aca69d797185c1702c637a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.249"

[options]
datapack-folder = "datapacks"
