name = "SMP 2026"
author = "TI7AN"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "668519427c16f2528a9514ea8eef95670d03d9dff7b65bb9c4d088a78d6d83a1"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.249"

[options]
datapack-folder = "datapacks"
